### ISSUE TITLE
screensaver.instagram doesn't work

### ISSUE THREAD

**Issue by tug912** [Lunatixz/KODI_Addons#10]
Tried it but doesn't work on PC or Raspberry Pi 3

**Comment by Lunatixz** [comment]
I'll look into it when I have some free time...

**Comment by smoak** [comment]
Looks like at least on Kodi 17.6 not all of the settings show up in the settings window. This means that they do not get set so the addon crashes when it tries to read them on line 43

**Comment by tredfoot** [comment]
Not working on a MAC, Kodi 18.X.

Settings panel working, uname password added, but it always uses "popeyethefoodie" instead of the overriden account to follow.  Also, the default popeyethefoodie doesn't work do to the following error:

ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://scontent-iad3-1.cdninstagram.com/vp/c3d5cedf1cdccf0160797091f78c6746/5B2934B9/t51.2885-15/e35/22858447_905318886298085_7142763761252696064_n.jp

Hopefully this helps!

**Comment by abcnorio** [comment]
...can confirm for LibreELEC for RPi as well as amd64 (LE Version >=9, Kodi >=18). Same error as 'tredfoot' reports, so it is completely broken. Seems the URL does not fit instagram's pattern anymore. Thanks for fixing this.

**Comment by Lunatixz** [comment]
Thanks for the info @smoak @tredfoot I've been busy... but i'll look into it.

**Comment by Sopor** [comment]
I tried to install this this screensaver on Kodi 18.7 but after pressing `preview` i was stuck and was forced to close Kodi to get out. I tried all keys and mouse buttons but it was only showing a big Instagram logo.
