### ISSUE TITLE
Hello, I was wondering if there are any good tutorial videos on Kodi add-on development. 

### ISSUE THREAD

**Issue by JoJenH** [Lunatixz/KODI_Addons#194]
Hello, I was wondering if there are any good tutorial videos on Kodi add-on development. The official Wiki is ten years old and is not a tutorial for Python 3. In addition, there is no immediate debugging in the development process. Do you know if there is a TUI interface similar to XBMCSwifT2? Thank you very much.

**Comment by Lunatixz** [comment]
No IDE specifically for Kodi; I personally use notepad+ since I'm familiar with Python.

If you are new to python I would recommend using pyCharm with [Kodi stubs](https://github.com/romanvm/Kodistubs).

Use the link below for Kodi API docs.
https://xbmc.github.io/docs.kodi.tv/master/kodi-base/de/d69/group__python.html
