### ISSUE TITLE
Please fix Pluto TV, and a few suggestions

### ISSUE THREAD

**Issue by CHJ85** [Lunatixz/KODI_Addons#55]
Hi there. 
Please fix the live channels and EPG on Pluto.
You may use my m3u:

Oh and also. On the XUMO tv addon, most of the channels aren't the actual channels but rather the current video. Do you think you could fix that?
Also, for your streams I see you're using the "dai2.xumo.com" url. But you can use "https://cinedigm.vo.llnwd.net/conssui" instead in order to bypass the expiration token.
There are a few exceptions though. Some of the redbox channels such as ShoutFactory TV, Rush and Mystery Science Theater 3000 use "-redbox.amagi.tv/hls/".

Anyway. Hit me back.

**Comment by Lunatixz** [comment]
I do not use m3u or xmltv lists. I parse data directly from the services API. I'll look into fixing any outstanding issues. Thx

**Comment by CHJ85** [comment]
Thanks. Unfortunately for me, I'm not good enough at programming yet. So using m3u and xmltv is the best I can do for now.

**Comment by Lunatixz** [comment]
I disagree there are no upsides to m3u lists. Direct API access is the proper solution to all development endeavors. Thx

**Comment by CHJ85** [comment]
Why did you delete that message?
Anyway. I don't disagree.
It's just that multiple addons = more storage and bloat. Especially on something like a Firestick, Kodi is slow enough as it is. And besides, the m3u and xmltv can be used in the tv guide.
The way I would of done it is use their API to generate the m3u and xmltv. Set up a cronjob to make sure they're always up to date and use these in your addons.
As you can see from the links I posted (and removed because search engines), that's my tactic.
Makes the addons run a lot faster too. When I use your XUMO addon now for instance, I have to wait forever just so it can load a few channels, because it's constantly calling back to their server.

**Comment by kekukui** [comment]
> **with m3u8's you have to make sure that the links are up to date... When I use your XUMO addon now for instance, I have to wait forever just so it can load a few channels, because it's constantly calling back to their server.  The way I would of done it is use their API to generate the m3u and xmltv.**

I guess you want to load this stuff into Kodi's simple PVR client.  That would not reduce the time it takes to download the EPG, but I think that using a PVR client is the right idea:

For maximum performance and easy installation, any channel directory like Pluto or Xumo should be implemented as a dedicated PVR client for Kodi or an EPG grabber for TVheadend, because the Kodi or TVheadend PVR manager can then combine all of your live TV sources into one master channel guide automatically.  The FilmOn PVR client is a good example of this (although it was broken the last time I checked, it did work in the past).  This would be a lot easier for the user than it is to install & configure multiple live TV addons and then configure another addon to collect the output from all of them, and then configure the 'PVR simple client' to find it.  And you still have the issue of the addon EPG collector backends possibly getting out of sync because they are not controlled by the PVR manager's scheduler.

Another problem is that Pluto & Xumo do not appear to support user accounts with favorite channels at this time, so you have to download the whole freaking catalog.  And you cannot submit new channels to the database (like you can with something like Ccloud, Channel PEAR, or Radio Browser.)  The thing that we really need most is a central public repository for video stream links and EPG data, so IPTV simple client or TVheadend can fetch everything from one place.  Then you could manage your IPTV lineup through a web interface and retrieve it on any device with a media player app that supports M3U/XMLTV.  This is what Kodi's PVR simple client was designed for.  The real place and purpose of conventional Kodi addons is the on-demand stuff, not collections of live IPTV channels.

Kodi PVR clients would also perform a bit better than regular addons because they are built with C++.  It kind of surprises me that developers of live stream addons are not doing much to leverage the power of the PVR managers in Kodi or TVheadend, since no other platform has the ability to easily and quickly assemble an EPG from both dedicated tuners **and** IPTV simultaneously, then format the channel lineup the way that you like and collect EPG data when you want it to.  They could also create a generic Kodi PVR client that accepts web site scrapers written in Python as plugins, and this PVR client could allow you to download those plugins from a central repository through a GUI menu.  That would permit developers to write scrapers which only output XML/M3U like you suggested.  It's easier to do this than it is to build a complete Kodi addon, then get it published in the official repo.  It would result in a better end user experience and many more EPG sources for Kodi.

Lunatixz has made a lot of great stuff, and better live stream / EPG support is just what Kodi needs.  Even if I dont watch much on Pluto, I think this is a very nice addon, and I expect the channel lineup to improve as time goes on.  If nothing else it is a good example, and a fine demonstration of Kodi's ability to reformat the web for a remote control interface.  However, I do agree that a universal solution could be devised which makes it unnecessary to create a complex addon with a built in GUI for every web site that has an EPG (or widgets that struggle to shoehorn data from multiple sources into a simple PVR client because it has no proper plugin support.)

**Comment by CHJ85** [comment]
Well. I did load the channels into Kodi's PVR Simple client.
But they decided to change it up again, so now some of the channels will not work without the SID token.
So I'm trying to figure out what the actual stream urls are so I can continue using Kodi.

**Comment by kekukui** [comment]
The problem with some some of these streams which use tokens is that the tokens change every hour (or at least once a day).  YouTube is an example of this - where tokens on live streams will change frequently.  So even if you can determine the actual stream URL and include the token, it will not continue to work for very long.  The solution for those channels is going to involve adding a "resolver" to get the stream URL+token from the page where it is embedded.  There is an app called 'SMplayer' that has a built in resolver to handle sites like this.  Unlike VLC (which supposedly "plays everything") you can actually paste in a YouTube **page** link and it will find and play the embedded **stream** link automatically.  It works on many pages that have an embedded live stream, and it should be possible to include support for this in Kodi - especially where there is only one embedded stream link per page URL.  Where there are multiple streams on a page, you would need to do some kind of pattern matching, so the line for that channel in your M3U file would need to contain a string which matches a channel name in the source of the web page.

**Comment by CHJ85** [comment]
@kekukui It's every half hour. But like I said, that's why I need to find the actual URL. I don't even know what encryption they use. 
Alternatively I could read up on their API and generate the m3u8's that way. But I'm lazy, so I might just try Wireshark.

**Comment by kekukui** [comment]
You mean like this?

`https://weathernation-plutolive-vo.akamaized.net/m/hlslive/weathernation-ak/3/weathernation-ak.m3u8?profID=393&n=3&ctype=0&chname=weathernation-ak&pub=cd44c23c-4796-475f-bcb1-b846bed4cf40&acsurl=pluto-acs-lb.adsparx.net&mcdn=weathernation-plutolive-vo.akamaized.net%2Fm`

I'm sure its been a half hour now.  What channels dont work?

**Comment by CHJ85** [comment]
Yea, that's the one you get from the source code.
This is the actual link: https://weathernation-plutolive-vo.akamaized.net/m/hlslive/weathernation-ak/3/weathernation-ak.m3u8?chname=weathernation&pub=0

**Comment by kekukui** [comment]
> **these are only the akamaized channels.**

I did not realize there was another host because I was not looking at the source, I was just logging traffic.  Give me an example of a channel which does not work reliably.  I dont necessarily need a link, just the name of a channel.

**Comment by CHJ85** [comment]
Okay. Try Andromeda. Channel ID 5e825635aeee3d000717ebbc.
So if you check the link in say VLC, you can see that it connects to the stream than blocks it.
http://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5e825635aeee3d000717ebbc/master.m3u8?deviceType=web&deviceMake=web&deviceModel=web&sid=4660&deviceId=5e825635aeee3d000717ebbc&deviceVersion=DNT&appVersion=DNT&deviceDNT=0&userId=&advertisingId=&deviceLat=&deviceLon=&app_name=&appName=web&buildVersion=&appStoreUrl=&architecture=&includeExtendedEvents=false&marketingRegion=US&serverSideAds=true

This is what I need to get around. It seems like what they're doing is only allow certain user agents. And if that's the case, then this would be on the CDN level. Meaning I either have to bypass the CDN or figure out which user-agents they use.

**Comment by kekukui** [comment]
I tried that link with a common browser user agent in VLC and it still did not work.  It does work in SMplayer without any "tweaks".  It also works in the Kodi Streamlink Tester addon* (which proves that Kodi can play it as-is.)  Are you claiming it does not work in your M3U file?

* https://raw.githubusercontent.com/Twilight0/repo.twilight0/master/_zips/repository.twilight0/repository.twilight0-1.1.0.zip

**Comment by CHJ85** [comment]
I already know that, dude.
I've already tried all the common user agents, which leads me to believe that they're piping the stream threw a specific user-agent and extracting it threw the DNS, which in this case would be service-stitcher, where they whitelist their own domain pluto.tv.
Either way, I have to bypass the DNS server and find out what the actual stream URL is.

**Comment by kekukui** [comment]
What the fuck are you going on about?!  These are **HLS** streams!  There is no _"**actual stream URL**"_ !! There are **_MULTIPLE_** stream URL's at **different bitrates**.

_"To enable a player to adapt to the bandwidth of the network, the original video is encoded in several distinct quality levels. The server serves an index, called a master playlist, of these encodings, called variant streams. **The player can then choose between the variant streams during playback, changing back and forth seamlessly as network conditions change.**"_

https://en.wikipedia.org/wiki/HTTP_Live_Streaming

The master playlist works in Kodi and it works in PVR simple client.  So _**WHAT IS YOUR ISSUE**_ ???????????

**Comment by CHJ85** [comment]
You really do not understand what I'm talking about, do you?
Btw, I did manage to find a working user-agent. So as I suspected, they've blocked the common ones on the server side and whitelisted only select domain names.
Should be easy enough to crack though, as they're most likely using .htaccess for that.
Anyway. A working user-agent (for now until they block it) is **Mozilla/5.0 (Linux; Android 9; MAR-LX3A Build/HUAWEIMAR-L03A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36 UOH/v1.5.4_223-android**.

**Comment by kekukui** [comment]
> **by "actual stream" I mean the actual stream URL, bypassing the CDN.**

The correct term for that would be "origin" or "source".  (And it's _"through_", not _"threw"_.)  I dont really care if you cant spell, but you do have a problem communicating clearly.  And what is the point of all this, if the CDN will give you better performance?  If you are running some kind of service, why are you bothering Lunatix about the addon?  Your initial complaint was that the addon wont work.  Now you are up to something else entirely.  Nothing makes sense because you keep changing the subject.

**Comment by CHJ85** [comment]
Okay mister "I'm awesome at grammar". Who cares? 😀 Also, are you any better? Using language? Now, I personally do not mind, but a lot of people do. And it's also very unprofessional.
Anyway, Origin and source wouldn't be the right terminologies either, because it's still the same source, but they pipe it through the CDN so that they can add all sorts of security and token encryption to it.
And my purpose for getting behind the CDN is to avoid their API which they seem to be changing a lot lately. And why would the stream perform better behind the CDN? Because they prefix the buffer settings within the m3u8? That is something I can fix myself.
Anyway. You said that the stream works in Kodi, which means they haven't blocked Kodi's user agent yet. But it's obviously only a matter of time before they do. And I don't wanna have to add different user agent strings to the m3u playlist file every other week just so I can watch their channels in Kodi. That's insane.

**Comment by kekukui** [comment]
> **my purpose for getting behind the CDN is to avoid their API which they seem to be changing a lot lately**

_Everything_ on the server side is subject to change.  But the one guarantee is that the links embedded in the web page are going to work the same way, if it uses HLS.  So if you are looking for the best reliability, its probably better to scrape the web site and do some pattern matching.  SMplayer works on many web pages with an embedded stream for exactly that reason.  There is no guarantee that your method will be more reliable.

> **You said that the stream works in Kodi, which means they haven't blocked Kodi's user agent yet. But it's obviously only a matter of time before they do.**

So what?  You can pass user agent strings to Kodi's media player.  And why would they block Kodi if they have apps for Roku & Apple TV?  They make their money from inserting ads, just like OTA channels.

> **And I don't wanna have to add different user agent strings to the m3u playlist file every other week**

If you use the string from a popular browser you wont have to do that.  And PVR simple can override the user agent, so you dont have to add it for every channel in the playlist.

**Comment by CHJ85** [comment]
>Everything on the server side is subject to change.
Rarely. Their API however do change a lot. Their link format hasn't changed once since they started.
>So what? You can pass user agent strings to Kodi's media player.
Which is what I'm doing. But what does that help when they block em all from accessing their servers?
>If you use the string from a popular browser you wont have to do that.
What language am I speaking here?
As I said, they're blocking em all on their end, allowing a few ones through (for now).
They'll eventually block Kodi as well. And all the common ones like browsers have already been blocked. I know this for a fact as I've tried almost 20 versions of both Chrome, Chromium, Firefox, Edge, Brave, Vivaldi and Internet Explorer. Out of all the ones I've tested, the one I mentioned above still works. The way they're able to stream their channels threw pluto.tv, therokuchannel and their apps is by making exception rules to the server's .htaccess file. That is why whatever browser you use, you'll be able to watch their streams so long as it goes through their site. If you try to embed the stream, it won't work.
Do you understand now why I have to do this? Yes it still works in Kodi and the Perfect Player. But for how long?

**Comment by kekukui** [comment]
> **Their API however do change a lot.  If you try to embed the stream, it won't work.**

I think one of the problems here is that you are talking about two different things and keep switching between them.  One is _**"the best way to fix the addon"**_, and the other is _**"the best way to make these channels work longer in PVR simple client."**_  An example of the former would be to create a Brightscript interpreter or Brightscript to Python translator, so all Roku apps would run on Kodi and then you dont have to maintain the addon.  An example of the latter would be to extend the functionality of PVR simple client so you can invoke a resolver for these channels in your M3U file.  Isnt that better than chasing streams forever?  Talk about crazy.

> **What language am I speaking here?**

That's a good question.  You did not communicate the issue clearly, and insulted me several times, but you call **me** "unprofessional."   However, I did not insult **you** for lack of advanced developer skills.  We each have different skill sets because the entire system is too complex for any one person to master.  Other core Kodi developers have already acknowledged this, and you should as well - because sometimes people still have ideas worth considering, or observations that inspire practical solutions.

**Comment by CHJ85** [comment]
No I'm actually not talking about two different things.
And that  snarky sarcasm of your ain't gonna get you far in life.
So stop acting like a know it all and stone that attitude of yours.

**Comment by CHJ85** [comment]
@Lunatixz Sorry this ticket turned into me commisurating with this kekukui clown.
Anyway. Do you think you could fix the XUMO plugin? Like I said, the live channels aren't live, but rather the current airing program starting at the beginning.
Only a few of these channels are actually live.
And the channel list loading time is crazy, if you could look into that as well.

**Comment by kekukui** [comment]
> **So stop acting like a know it all and stone that attitude of yours.**

Funny I was thinking the same:  You seem to think that no one else should be allowed to express an opinion thats different from your own - and when they do, you accuse them of trying to show off.

>**Sorry this ticket turned into me commisurating with this kekukui clown.**

Too bad there isn't a badge for _'first ad-hominem attack'_. 🤡

> **They'll eventually block Kodi as well.**

I think my point was valid, and it still is:  That example stream link which you "need to get around" still works.  They are not trying to block Kodi.  I see commercial breaks here... which means that this site is an advertiser-supported platform, and their business model is based on expanding the viewer base so they can attract larger advertisers which spend a lot of money.  If they want to be successful at this, they should **_promote_** the Kodi app!

Now I could be wrong if they decide to "block Kodi" some day - but I fail to see what would be the justification for blocking viewers of **any** kind in the same region, where the advertising is embedded in the stream.  The streams might be geo-restricted, but that is a whole different issue.  They just dont want to spend bandwidth on foreign markets... and there are solutions for that on both the client & server side.
