### ISSUE TITLE
Please update Locast

### ISSUE THREAD

**Issue by CHJ85** [Lunatixz/KODI_Addons#59]
Hi there. Please update the Locast addon.
It stopped working some time ago.
Now when I log in, it just takes me to Kodi's addon menu.

**Comment by Goldenfreddy0703** [comment]
Im begging too for the NewsOn addon but sadly i see why they stop the updates on it. It was basically the NewsOn Website because it changed now in which you have to download their apps sadly. I'm not sure what the addon developer is going to do but i support him and his work and what he has done so far.

**Comment by Goldenfreddy0703** [comment]
> 
> 
> Hi there. Please update the Locast addon.
> It stopped working some time ago.
> Now when I log in, it just takes me to Kodi's addon menu.

oh btw you should try Kodi Solutions, its only 5$ a month and you get Live TV with 4000 channels and they provide US and UK Channels and a whole bunch of categories and it doesn't lag. 
Here is a website if you wanna check it out: https://www.ks-hosting.com

**Comment by Lunatixz** [comment]
I'll look into it... they changed some of there backend endpoints; haven't had the time to look into it.
